### ISSUE TITLE
Error while creating a new course

### ISSUE THREAD

**Issue by combefis** [combefis/ECM#5]
When creating a new course, without filling anything, an error occurred (because of the missing coordinator...)

**Comment by AlexisTM** [comment]
Issue corrected at  : 1ff363a65b329e1b8d477850092f9085ab08db58

**Comment by combefis** [comment]
There is still an error, the course that is entered in now just ignored when creating a new exam.

**Comment by combefis** [comment]
Fixed by commit ecb9cdcf66fae7a62cce4a1f191a66de4e071da8
